<!DOCTYPE html>
<html id="%%path_insert%%">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width" />

<meta name="generator" content="Info v%%info_version%%" />

<title>%%info_title%%</title>
<meta name="author" content="%%info_author%%" />
<meta name="description" content="%%info_description%%" />

<link href="%%info_path%%inc/css/css.css" rel="stylesheet" type="text/css" media="all" />%%extra_css%%
</head>
<body id="%%page%%" class="%%flags%%">
