<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta http-equiv="Content-Language" content="en-GB" />	
<meta name="viewport" content="width=device-width" />

<meta name="generator" content="Info v%%info_version%%" />
<meta name="copyright" content="%%info_copyright%%" />

<title>%%info_title%%</title>
<meta name="author" content="%%info_author%%" />
<meta name="description" content="%%info_description%%" />

<link href="%%info_path%%inc/css/css.css" rel="stylesheet" type="text/css" media="all" />%%extra_css%%
</head>
<body class="%%flags%%" path="%%path_insert%%">
